"""Generate the inner pages from the shell used by index.html so the header,
footer and script tags can never drift between pages.

The output is plain, hand-editable HTML: this script exists only to avoid
duplicating ~200 lines of header/footer markup six times.

usage: python tools/build_pages.py
"""
import re
import sys

ROOT = "."
INDEX = "index.html"

NOTE = ("<!-- Generated by tools/build_pages.py from the shell in index.html.\n"
        "     Edit the shared shell there, or edit this file directly. -->")


def main():
    src = open(INDEX, encoding="utf-8").read()

    head_match = re.search(r'<link rel="stylesheet" href="assets/css/style.css">', src)
    if not head_match:
        sys.exit("could not find the stylesheet link in index.html")
    stylesheets = ('<link rel="stylesheet" href="assets/css/fonts-sarabun.css">\n'
                   '<link rel="stylesheet" href="assets/css/fonts-cairo.css">\n'
                   '<link rel="stylesheet" href="assets/css/style.css">')

    header = re.search(r"<!-- =+ HEADER =+ -->.*?</header>", src, re.S).group(0)
    footer = re.search(r"<!-- =+ FOOTER =+ -->.*</html>", src, re.S).group(0)

    for page in PAGES:
        active_header = set_active(header, page["nav"])
        html = (HEAD.format(
            lang="en",
            title=page["title"],
            description=page["description"],
            stylesheets=stylesheets,
            header=active_header,
            main=pagehead(page) + "\n" + page["body"],
            footer=footer,
        ))
        out = page["file"]
        with open(out, "w", encoding="utf-8") as f:
            f.write(html)
        print(f"  {out}  ({len(html)} bytes)")


def set_active(header, href):
    h = header.replace(' class="nav__item is-current"', ' class="nav__item"')
    needle = '<li class="nav__item"><a class="nav__link" href="%s"' % href
    if needle not in h:
        raise SystemExit("nav item not found: %s" % href)
    return h.replace(needle, '<li class="nav__item is-current"><a class="nav__link" href="%s"' % href, 1)


def pagehead(page):
    return """
  <section class="page-head" style="background-image:url('%(bg)s')">
    <div class="page-head__inner container">
      <span class="eyebrow" data-i18n="%(eyebrow)s">%(eyebrow_en)s</span>
      <h1 class="page-head__title" data-i18n="%(title_key)s">%(h1)s</h1>
      <nav class="breadcrumb" aria-label="Breadcrumb">
        <a href="index.html" data-i18n="breadcrumb.home">Home</a>
        <span class="breadcrumb__sep">/</span>
        <span aria-current="page" data-i18n="%(title_key)s">%(h1)s</span>
      </nav>
    </div>
  </section>""" % page


HEAD = """<!DOCTYPE html>
<html lang="{lang}" dir="ltr" data-lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<meta name="description" content="{description}">
<link rel="icon" href="assets/logo/favicon.png" type="image/png">
<link rel="apple-touch-icon" href="assets/logo/favicon.png">
{stylesheets}
</head>
<body>

<a class="skip-link" href="#main" data-i18n="nav.skip">Skip to content</a>

{header}

<main id="main">
{main}
</main>

{footer}
"""


# --------------------------------------------------------------------------
# shared section fragments
# --------------------------------------------------------------------------
CTA = """
  <section class="band" style="background-image:url('assets/img/cta.jpg')">
    <div class="band__inner container" data-reveal>
      <span class="eyebrow eyebrow--plain" data-i18n="contact.eyebrow">Get in touch</span>
      <blockquote data-i18n="cta.title" style="font-size:64px">Thank you</blockquote>
      <p class="lead" style="color:rgba(255,255,255,.82);max-width:640px;margin:0 auto 32px" data-i18n="cta.text">Thank you for your trust. We are ready to support your business with end-to-end logistics solutions, from warehousing to your customer's door.</p>
      <a class="btn" href="get-in-touch.html" data-i18n="cta.button">Start with us</a>
    </div>
  </section>"""

STATS = """
  <section class="section section--soft">
    <div class="container">
      <div class="section-head section-head--center" data-reveal>
        <span class="eyebrow" data-i18n="stats.eyebrow">By the numbers</span>
        <h2 data-i18n="stats.title">Our logistics capability</h2>
      </div>
      <div class="stats">
        <div class="stat" data-reveal>
          <div class="stat__value"><span data-count-to="12"></span><span>+</span></div>
          <div class="stat__label" data-i18n="stats.value1">Warehouses</div>
        </div>
        <div class="stat" data-reveal data-reveal-delay="90">
          <div class="stat__value"><span data-count-to="85"></span><span>+</span></div>
          <div class="stat__label" data-i18n="stats.value2">Transport fleet</div>
        </div>
        <div class="stat" data-reveal data-reveal-delay="180">
          <div class="stat__value"><span data-count-to="240"></span><span>+</span></div>
          <div class="stat__label" data-i18n="stats.value3">Team members</div>
        </div>
        <div class="stat" data-reveal data-reveal-delay="270">
          <div class="stat__value"><span data-count-to="99"></span><span>%</span></div>
          <div class="stat__label" data-i18n="stats.value4">Accuracy rate</div>
        </div>
      </div>
    </div>
  </section>"""

MISSION_VISION = """
  <section class="section section--band">
    <div class="container">
      <div class="cards" style="grid-template-columns:repeat(2,1fr);gap:40px">
        <article class="card" data-reveal>
          <div class="card__icon">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true">
              <circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="4"/><circle cx="12" cy="12" r="1" fill="currentColor"/>
            </svg>
          </div>
          <h3 data-i18n="mission.title">Our Mission</h3>
          <p data-i18n="mission.text">Providing logistical support for trading companies to maintain their sustainability, facilitate the flow of goods between suppliers and markets to final consumers, and prevent the supply chain from stopping or being obstructed.</p>
        </article>
        <article class="card" data-reveal data-reveal-delay="120">
          <div class="card__icon">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true">
              <path d="M2 12s3.6-6 10-6 10 6 10 6-3.6 6-10 6-10-6-10-6z"/><circle cx="12" cy="12" r="2.6"/>
            </svg>
          </div>
          <h3 data-i18n="vision.title">Our Vision</h3>
          <p data-i18n="vision.text">To be an ideal, safe and professional logistics environment with the highest level of equipped transport and distribution fleets, to serve customers and achieve their goals — a leader in its field and a pioneer in the region.</p>
        </article>
      </div>
    </div>
  </section>"""

VALUES = """
  <section class="section">
    <div class="container">
      <div class="split">
        <div class="split__media" data-reveal>
          <img src="assets/img/values.jpg" alt="Warehouse operations at ING Logistics" width="1920" height="1177" loading="lazy">
        </div>
        <div class="split__body" data-reveal data-reveal-delay="120">
          <div class="section-head">
            <span class="eyebrow" data-i18n="values.eyebrow">Our Values</span>
            <h2 data-i18n="values.title">Our Values</h2>
            <p data-i18n="values.text">Our values at ING are honesty and trust, sincerity, integrity and partnership in pursuit of productivity.</p>
          </div>
          <ul class="value-list">
            <li>
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="M20 6L9 17l-5-5"/></svg>
              <div><strong data-i18n="values.item1.title">Honesty and trust</strong>
              <span data-i18n="values.item1.text">Honesty in words and deeds, and trust in everything we do with our clients and partners.</span></div>
            </li>
            <li>
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="M20 6L9 17l-5-5"/></svg>
              <div><strong data-i18n="values.item2.title">Sincerity in work</strong>
              <span data-i18n="values.item2.text">Sincerity and dedication in delivering a service worthy of our clients' trust.</span></div>
            </li>
            <li>
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="M20 6L9 17l-5-5"/></svg>
              <div><strong data-i18n="values.item3.title">Integrity</strong>
              <span data-i18n="values.item3.text">Transparency and integrity in every dealing, and commitment to professional standards.</span></div>
            </li>
            <li>
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="M20 6L9 17l-5-5"/></svg>
              <div><strong data-i18n="values.item4.title">Partnership and productivity</strong>
              <span data-i18n="values.item4.text">One-team spirit and participation in hard work to achieve productivity.</span></div>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </section>"""

STORIES = """
  <section class="section">
    <div class="container">
      <div class="split split--reverse">
        <div class="split__media split__media--offset" data-reveal>
          <img src="assets/img/story.jpg" alt="ING Logistics operations" width="1400" height="1400" loading="lazy">
        </div>
        <div class="split__body" data-reveal data-reveal-delay="120">
          <div class="section-head">
            <span class="eyebrow" data-i18n="story.eyebrow">Get to know us</span>
            <h2 data-i18n="story.title">Our Story</h2>
          </div>
          <p data-i18n="story.text">In light of the rapid development of the people and the world, and the quantum leap of the global economic market, we decided to join the development and create a logistics revolution that reflects continuous growth and development — by creating a company dedicated to providing innovative, professional, modern solutions to become the distinctive mark in warehousing and logistics services.</p>
        </div>
      </div>
    </div>
  </section>"""


def faq_section():
    return """
  <section class="section">
    <div class="container">
      <div class="section-head" data-reveal>
        <span class="eyebrow" data-i18n="faq.eyebrow">Frequently asked</span>
        <h2 data-i18n="faq.title">Questions we are often asked</h2>
      </div>
      <div class="accordion" data-reveal>
        %s
      </div>
    </div>
  </section>""" % "\n        ".join(
        """
        <div class="accordion__item">
          <button class="accordion__trigger" type="button">
            <span data-i18n="faq.q%d">%s</span>
            <span class="accordion__icon" aria-hidden="true">
              <svg viewBox="0 0 24 24" width="14" height="14" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 5v14M5 12h14"/></svg>
            </span>
          </button>
          <div class="accordion__panel"><div data-i18n="faq.a%d">%s</div></div>
        </div>""" % (i, q, i, a)
        for i, (q, a) in enumerate([
            ("What services does ING provide?",
             "ING provides warehouse services management, loading and unloading, sorting and grouping, packaging, follow-up on damaged goods and returns, as well as delivery and distribution, track and trace, and various offices for work."),
            ("Can I track my shipment?",
             "Yes. ING provides a track and trace service that lets customers follow the status of their order from receipt through to delivery."),
            ("Who are ING's clients?",
             "We serve trading companies, wholesalers, retailers and hypermarkets, businesspeople and entrepreneurs, and the company selects its clients with great care and consideration."),
            ("How do I start working with you?",
             "Get in touch using the contact details below and our team will review your requirements and propose the right logistics solution."),
        ], 1)
    )


# --------------------------------------------------------------------------
# pages
# --------------------------------------------------------------------------
PAGES = [
    dict(
        file="about-us.html",
        nav="about-us.html",
        title="About Us — ING Logistics",
        description="The story, mission, vision and values behind ING Logistics: honest, professional and safe logistics services.",
        bg="assets/img/services-hero.jpg",
        eyebrow="about.eyebrow", eyebrow_en="Who we are",
        title_key="about.title", h1="About Us",
        body=STORIES + MISSION_VISION + VALUES + STATS + CTA,
    ),
    dict(
        file="our-services.html",
        nav="our-services.html",
        title="Our Services — ING Logistics",
        description="Warehouse services management, delivery and distribution, track and trace, and versatile workspaces from ING Logistics.",
        bg="assets/img/services-intro.jpg",
        eyebrow="pageServices.eyebrow", eyebrow_en="What we do",
        title_key="pageServices.title", h1="Our Services",
        body="""
  <section class="section">
    <div class="container">
      <div class="section-head section-head--center" data-reveal>
        <span class="eyebrow" data-i18n="services.eyebrow">What we do</span>
        <h2 data-i18n="services.title">Our Services</h2>
        <p data-i18n="services.text">Providing logistical support for trading companies to maintain their sustainability, facilitate the flow of goods between suppliers and markets to final consumers, and prevent the supply chain from stopping or being obstructed.</p>
      </div>

      <div class="split" style="margin-top:20px">
        <div class="split__media" data-reveal>
          <img src="assets/img/services-hero.jpg" alt="ING Logistics fleet and warehouse" width="1920" height="1280" loading="lazy">
        </div>
        <div class="split__body" data-reveal data-reveal-delay="120">
          <h3 data-i18n="warehouse.title">Warehouse Services Management</h3>
          <p data-i18n="warehouse.text">We run warehouse services to a high standard with a dedicated team and equipped space, so your goods arrive safely and on time.</p>
          <ul class="value-list">
            <li><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="M20 6L9 17l-5-5"/></svg><div><strong data-i18n="warehouse.item1.title">Upload and download</strong><span data-i18n="warehouse.item1.text">Dedicated loading and unloading teams working to full safety standards.</span></div></li>
            <li><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="M20 6L9 17l-5-5"/></svg><div><strong data-i18n="warehouse.item2.title">Sorting and grouping</strong><span data-i18n="warehouse.item2.text">Accurate sorting and consolidation of shipments by destination and requirements.</span></div></li>
            <li><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="M20 6L9 17l-5-5"/></svg><div><strong data-i18n="warehouse.item3.title">Packaging</strong><span data-i18n="warehouse.item3.text">Professional packing and packaging that keeps goods intact until delivery.</span></div></li>
            <li><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="M20 6L9 17l-5-5"/></svg><div><strong data-i18n="warehouse.item4.title">Follow up on damaged goods and returns</strong><span data-i18n="warehouse.item4.text">Close follow-up and efficient handling of damaged goods and returns.</span></div></li>
          </ul>
        </div>
      </div>
    </div>
  </section>

  <section class="section section--soft" id="warehouse">
    <div class="container">
      <div class="section-head" data-reveal>
        <span class="eyebrow" data-i18n="warehouse.eyebrow">Warehouse Services Management</span>
        <h2 data-i18n="services.title">Our Services</h2>
      </div>
      <div class="feature" id="delivery" data-reveal>
        <div class="feature__num">01</div>
        <div class="feature__body">
          <h3 data-i18n="delivery.title">Delivery and Distribution</h3>
          <p data-i18n="delivery.text">Provides support and assistance to trading companies by delivering products from suppliers to wholesalers, retailers and hypermarkets.</p>
        </div>
      </div>
      <div class="feature" id="track" data-reveal>
        <div class="feature__num">02</div>
        <div class="feature__body">
          <h3 data-i18n="track.title">Track and Trace</h3>
          <p data-i18n="track.text">This service allows our customers to track the status of their order from receipt to delivery.</p>
        </div>
      </div>
      <div class="feature" id="offices" data-reveal>
        <div class="feature__num">03</div>
        <div class="feature__body">
          <h3 data-i18n="offices.title">Various Offices for Work</h3>
          <p data-i18n="offices.text">It offers administrative offices, meeting spaces and training halls furnished with all the necessary equipment, in a range of sizes to serve the company's customers, businesspeople and entrepreneurs.</p>
        </div>
      </div>
    </div>
  </section>

  <section class="band" style="background-image:url('assets/img/slide-4.jpg')">
    <div class="band__inner container" data-reveal>
      <blockquote data-i18n="about.heading">Modern logistics solutions for trading companies</blockquote>
      <cite data-i18n="footer.slogan">To be an ideal, safe and professional logistics environment.</cite>
    </div>
  </section>
""" + faq_section() + CTA,
    ),
    dict(
        file="our-clients.html",
        nav="our-clients.html",
        title="Our Clients — ING Logistics",
        description="The partners ING Logistics serves: trading companies, wholesalers, retailers, hypermarkets, businesspeople and entrepreneurs.",
        bg="assets/img/slide-2.jpg",
        eyebrow="pageClients.eyebrow", eyebrow_en="Our partners",
        title_key="pageClients.title", h1="Our Clients",
        body="""
  <section class="section">
    <div class="container">
      <div class="split">
        <div class="split__media" data-reveal>
          <img src="assets/img/services-intro.jpg" alt="ING Logistics distribution operations" width="1600" height="1068" loading="lazy">
        </div>
        <div class="split__body" data-reveal data-reveal-delay="120">
          <div class="section-head">
            <span class="eyebrow" data-i18n="clients.eyebrow">Our partners</span>
            <h2 data-i18n="clients.title">Our Clients</h2>
            <p data-i18n="clients.text">It selects its clients with great care and consideration, since our mission is to offer our clients quick, high-quality services that will set us apart from competitors in the logistics services industry.</p>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section class="section section--soft">
    <div class="container">
      <div class="client-grid" data-reveal>
        <div><span class="client-name" data-i18n="clients.c1">Trading companies</span></div>
        <div><span class="client-name" data-i18n="clients.c2">Wholesalers</span></div>
        <div><span class="client-name" data-i18n="clients.c3">Retailers</span></div>
        <div><span class="client-name" data-i18n="clients.c4">Hypermarkets</span></div>
        <div><span class="client-name" data-i18n="clients.c5">Suppliers</span></div>
        <div><span class="client-name" data-i18n="clients.c6">Businesspeople</span></div>
        <div><span class="client-name" data-i18n="clients.c7">Entrepreneurs</span></div>
        <div><span class="client-name" data-i18n="clients.c8">Final consumers</span></div>
      </div>
    </div>
  </section>
""" + STATS + CTA,
    ),
    dict(
        file="our-team.html",
        nav="our-team.html",
        title="Our Team — ING Logistics",
        description="The strong, professional team behind ING Logistics: ambition, expertise and in-depth logistics experience.",
        bg="assets/img/slide-3.jpg",
        eyebrow="pageTeam.eyebrow", eyebrow_en="Who we work with",
        title_key="pageTeam.title", h1="Our Team",
        body="""
  <section class="section">
    <div class="container">
      <div class="section-head section-head--center" data-reveal>
        <span class="eyebrow" data-i18n="team.eyebrow">Who we work with</span>
        <h2 data-i18n="team.title">Our Team</h2>
        <p data-i18n="team.text">By combining individuals with ambition, expertise and in-depth experience in the field of logistics services with the spirit of youth impetuous for innovation and change, it works to create a strong and professional team.</p>
      </div>

      <div class="team-grid">
        <article class="member" data-reveal>
          <div class="member__avatar" aria-hidden="true">EX</div>
          <h3 data-i18n="team.role1">Executive management</h3>
          <span data-i18n="stats.value3">Team members</span>
          <p data-i18n="team.desc1">Strategic leadership that builds partnerships and delivers sustainable growth.</p>
        </article>
        <article class="member" data-reveal data-reveal-delay="90">
          <div class="member__avatar" aria-hidden="true">OP</div>
          <h3 data-i18n="team.role2">Operations management</h3>
          <span data-i18n="stats.value3">Team members</span>
          <p data-i18n="team.desc2">Smooth daily planning and execution of every shipping and storage operation.</p>
        </article>
        <article class="member" data-reveal data-reveal-delay="180">
          <div class="member__avatar" aria-hidden="true">WH</div>
          <h3 data-i18n="team.role3">Warehouse management</h3>
          <span data-i18n="stats.value3">Team members</span>
          <p data-i18n="team.desc3">Managing space and equipment to keep the supply chain efficient.</p>
        </article>
        <article class="member" data-reveal data-reveal-delay="270">
          <div class="member__avatar" aria-hidden="true">CS</div>
          <h3 data-i18n="team.role4">Customer service</h3>
          <span data-i18n="stats.value3">Team members</span>
          <p data-i18n="team.desc4">Continuous support and close follow-up on orders and returns.</p>
        </article>
        <article class="member" data-reveal>
          <div class="member__avatar" aria-hidden="true">FL</div>
          <h3 data-i18n="team.role5">Transport fleet</h3>
          <span data-i18n="stats.value3">Team members</span>
          <p data-i18n="team.desc5">A fleet equipped to the highest standard to cover transport and distribution.</p>
        </article>
        <article class="member" data-reveal data-reveal-delay="90">
          <div class="member__avatar" aria-hidden="true">IT</div>
          <h3 data-i18n="team.role6">Information technology</h3>
          <span data-i18n="stats.value3">Team members</span>
          <p data-i18n="team.desc6">Track and trace systems that connect customers to their shipments live.</p>
        </article>
        <article class="member" data-reveal data-reveal-delay="180">
          <div class="member__avatar" aria-hidden="true">QS</div>
          <h3 data-i18n="team.role7">Quality and safety</h3>
          <span data-i18n="stats.value3">Team members</span>
          <p data-i18n="team.desc7">Commitment to quality and safety standards at every stage.</p>
        </article>
        <article class="member" data-reveal data-reveal-delay="270">
          <div class="member__avatar" aria-hidden="true">BD</div>
          <h3 data-i18n="team.role8">Business development</h3>
          <span data-i18n="stats.value3">Team members</span>
          <p data-i18n="team.desc8">Logistics solutions shaped around each client's needs.</p>
        </article>
      </div>
    </div>
  </section>
""" + VALUES + CTA,
    ),
    dict(
        file="get-in-touch.html",
        nav="get-in-touch.html",
        title="Contact — ING Logistics",
        description="Contact ING Logistics about warehousing, delivery and distribution, track and trace, or workspaces.",
        bg="assets/img/cta.jpg",
        eyebrow="pageContact.eyebrow", eyebrow_en="Get in touch",
        title_key="pageContact.title", h1="Contact",
        body="""
  <section class="section">
    <div class="container">
      <div class="contact-grid">
        <div data-reveal>
          <div class="section-head">
            <span class="eyebrow" data-i18n="contact.eyebrow">Get in touch</span>
            <h2 data-i18n="contact.title">How can we help you?</h2>
            <p data-i18n="contact.text">Tell us about your logistics requirement and our team will get back to you as soon as possible.</p>
          </div>

          <form class="form" data-demo-form novalidate>
            <div class="form__row">
              <label class="field">
                <span data-i18n="contact.formName">Full name</span>
                <input type="text" name="name" required autocomplete="name">
              </label>
              <label class="field">
                <span data-i18n="contact.formEmail">Email address</span>
                <input type="email" name="email" required autocomplete="email">
              </label>
            </div>
            <div class="form__row">
              <label class="field">
                <span data-i18n="contact.formPhone">Mobile number</span>
                <input type="tel" name="phone" autocomplete="tel">
              </label>
              <label class="field">
                <span data-i18n="contact.formService">Service required</span>
                <select name="service">
                  <option value="" data-i18n="contact.selectPlaceholder">Choose a service</option>
                  <option value="warehouse" data-i18n="contact.service.warehouse">Warehouse Services Management</option>
                  <option value="delivery" data-i18n="contact.service.delivery">Delivery and Distribution</option>
                  <option value="track" data-i18n="contact.service.track">Track and Trace</option>
                  <option value="offices" data-i18n="contact.service.offices">Various Offices for Work</option>
                </select>
              </label>
            </div>
            <label class="field">
              <span data-i18n="contact.formMessage">Your message</span>
              <textarea name="message" required></textarea>
            </label>
            <div>
              <button class="btn" type="submit" data-i18n="contact.formSubmit">Send message</button>
            </div>
            <p class="form__note" data-i18n="contact.formNote">This is a demo form and does not send data to any server.</p>
            <p class="form__status" role="status" aria-live="polite"></p>
          </form>
        </div>

        <div data-reveal data-reveal-delay="120">
          <ul class="info-list">
            <li>
              <div class="card__icon">
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true"><path d="M12 22s7-6.2 7-12a7 7 0 1 0-14 0c0 5.8 7 12 7 12z"/><circle cx="12" cy="10" r="2.6"/></svg>
              </div>
              <div><strong data-i18n="contact.addressLabel">Address</strong>
              <a href="https://maps.google.com/?q=32.51422635237183,35.94295766426107" target="_blank" rel="noopener" dir="ltr" data-i18n="contact.address">32.514226, 35.942958</a></div>
            </li>
            <li>
              <div class="card__icon">
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true"><path d="M5 4h4l2 5-2.5 1.5a12 12 0 0 0 5 5L15 13l5 2v4a1 1 0 0 1-1 1A16 16 0 0 1 4 5a1 1 0 0 1 1-1z"/></svg>
              </div>
              <div><strong data-i18n="contact.phoneLabel">Phone</strong>
              <a href="tel:+962799723777" dir="ltr">0799723777</a></div>
            </li>
            <li>
              <div class="card__icon">
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true"><rect x="3" y="5" width="18" height="14" rx="2"/><path d="M3 7l9 6 9-6"/></svg>
              </div>
              <div><strong data-i18n="contact.emailLabel">Email</strong>
              <a href="mailto:info@ing-logistics.com" dir="ltr">info@ing-logistics.com</a></div>
            </li>
            <li>
              <div class="card__icon">
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true"><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3.5 2"/></svg>
              </div>
              <div><strong data-i18n="contact.hoursLabel">Opening hours</strong>
              <span data-i18n="contact.hours">Saturday – Thursday: 8:00 AM – 5:00 PM</span></div>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </section>
""" + faq_section() + CTA,
    ),
]

if __name__ == "__main__":
    main()
